// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package functions

import (
	"context"
	"sync"
)

// Ensure, that FuncRegistryMock does implement FuncRegistry.
// If this is not the case, regenerate this file with moq.
var _ FuncRegistry = &FuncRegistryMock{}

// FuncRegistryMock is a mock implementation of FuncRegistry.
//
//	func TestSomethingThatUsesFuncRegistry(t *testing.T) {
//
//		// make and configure a mocked FuncRegistry
//		mockedFuncRegistry := &FuncRegistryMock{
//			FindFunc: func(ctx context.Context, matchers ...RegistryMatcherFunc) ([]Function, error) {
//				panic("mock out the Find method")
//			},
//			GetFunc: func(ctx context.Context, functionID string) (Function, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedFuncRegistry in code that requires FuncRegistry
//		// and then make assertions.
//
//	}
type FuncRegistryMock struct {
	// FindFunc mocks the Find method.
	FindFunc func(ctx context.Context, matchers ...RegistryMatcherFunc) ([]Function, error)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, functionID string) (Function, error)

	// calls tracks calls to the methods.
	calls struct {
		// Find holds details about calls to the Find method.
		Find []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Matchers is the matchers argument value.
			Matchers []RegistryMatcherFunc
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// FunctionID is the functionID argument value.
			FunctionID string
		}
	}
	lockFind sync.RWMutex
	lockGet  sync.RWMutex
}

// Find calls FindFunc.
func (mock *FuncRegistryMock) Find(ctx context.Context, matchers ...RegistryMatcherFunc) ([]Function, error) {
	if mock.FindFunc == nil {
		panic("FuncRegistryMock.FindFunc: method is nil but FuncRegistry.Find was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Matchers []RegistryMatcherFunc
	}{
		Ctx:      ctx,
		Matchers: matchers,
	}
	mock.lockFind.Lock()
	mock.calls.Find = append(mock.calls.Find, callInfo)
	mock.lockFind.Unlock()
	return mock.FindFunc(ctx, matchers...)
}

// FindCalls gets all the calls that were made to Find.
// Check the length with:
//
//	len(mockedFuncRegistry.FindCalls())
func (mock *FuncRegistryMock) FindCalls() []struct {
	Ctx      context.Context
	Matchers []RegistryMatcherFunc
} {
	var calls []struct {
		Ctx      context.Context
		Matchers []RegistryMatcherFunc
	}
	mock.lockFind.RLock()
	calls = mock.calls.Find
	mock.lockFind.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *FuncRegistryMock) Get(ctx context.Context, functionID string) (Function, error) {
	if mock.GetFunc == nil {
		panic("FuncRegistryMock.GetFunc: method is nil but FuncRegistry.Get was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		FunctionID string
	}{
		Ctx:        ctx,
		FunctionID: functionID,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, functionID)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedFuncRegistry.GetCalls())
func (mock *FuncRegistryMock) GetCalls() []struct {
	Ctx        context.Context
	FunctionID string
} {
	var calls []struct {
		Ctx        context.Context
		FunctionID string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
