// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package repository

import (
	"context"
	"github.com/diwise/iot-core/internal/pkg/infrastructure/database/rules"
	"sync"
)

// Ensure, that RuleRepositoryMock does implement RuleRepository.
// If this is not the case, regenerate this file with moq.
var _ RuleRepository = &RuleRepositoryMock{}

// RuleRepositoryMock is a mock implementation of RuleRepository.
//
//	func TestSomethingThatUsesRuleRepository(t *testing.T) {
//
//		// make and configure a mocked RuleRepository
//		mockedRuleRepository := &RuleRepositoryMock{
//			AddFunc: func(ctx context.Context, rule rules.Rule) error {
//				panic("mock out the Add method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) []rules.Rule {
//				panic("mock out the Get method")
//			},
//			UpdateFunc: func(ctx context.Context, rule rules.Rule) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedRuleRepository in code that requires RuleRepository
//		// and then make assertions.
//
//	}
type RuleRepositoryMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, rule rules.Rule) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) []rules.Rule

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, rule rules.Rule) error

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rule is the rule argument value.
			Rule rules.Rule
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rule is the rule argument value.
			Rule rules.Rule
		}
	}
	lockAdd    sync.RWMutex
	lockDelete sync.RWMutex
	lockGet    sync.RWMutex
	lockUpdate sync.RWMutex
}

// Add calls AddFunc.
func (mock *RuleRepositoryMock) Add(ctx context.Context, rule rules.Rule) error {
	if mock.AddFunc == nil {
		panic("RuleRepositoryMock.AddFunc: method is nil but RuleRepository.Add was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Rule rules.Rule
	}{
		Ctx:  ctx,
		Rule: rule,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, rule)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedRuleRepository.AddCalls())
func (mock *RuleRepositoryMock) AddCalls() []struct {
	Ctx  context.Context
	Rule rules.Rule
} {
	var calls []struct {
		Ctx  context.Context
		Rule rules.Rule
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RuleRepositoryMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("RuleRepositoryMock.DeleteFunc: method is nil but RuleRepository.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRuleRepository.DeleteCalls())
func (mock *RuleRepositoryMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RuleRepositoryMock) Get(ctx context.Context, id string) []rules.Rule {
	if mock.GetFunc == nil {
		panic("RuleRepositoryMock.GetFunc: method is nil but RuleRepository.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRuleRepository.GetCalls())
func (mock *RuleRepositoryMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RuleRepositoryMock) Update(ctx context.Context, rule rules.Rule) error {
	if mock.UpdateFunc == nil {
		panic("RuleRepositoryMock.UpdateFunc: method is nil but RuleRepository.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Rule rules.Rule
	}{
		Ctx:  ctx,
		Rule: rule,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, rule)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedRuleRepository.UpdateCalls())
func (mock *RuleRepositoryMock) UpdateCalls() []struct {
	Ctx  context.Context
	Rule rules.Rule
} {
	var calls []struct {
		Ctx  context.Context
		Rule rules.Rule
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
