// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package database

import (
	"context"
	"sync"
	"time"
)

// Ensure, that FuncStorageMock does implement FuncStorage.
// If this is not the case, regenerate this file with moq.
var _ FuncStorage = &FuncStorageMock{}

// FuncStorageMock is a mock implementation of FuncStorage.
//
//	func TestSomethingThatUsesFuncStorage(t *testing.T) {
//
//		// make and configure a mocked FuncStorage
//		mockedFuncStorage := &FuncStorageMock{
//			AddFunc: func(ctx context.Context, id string, label string, value float64, timestamp time.Time) error {
//				panic("mock out the Add method")
//			},
//			AddFnctFunc: func(ctx context.Context, id string, fnType string, subType string, tenant string, source string, lat float64, lon float64) error {
//				panic("mock out the AddFnct method")
//			},
//			HistoryFunc: func(ctx context.Context, id string, label string, lastN int) ([]LogValue, error) {
//				panic("mock out the History method")
//			},
//			InitializeFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Initialize method")
//			},
//		}
//
//		// use mockedFuncStorage in code that requires FuncStorage
//		// and then make assertions.
//
//	}
type FuncStorageMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, id string, label string, value float64, timestamp time.Time) error

	// AddFnctFunc mocks the AddFnct method.
	AddFnctFunc func(ctx context.Context, id string, fnType string, subType string, tenant string, source string, lat float64, lon float64) error

	// HistoryFunc mocks the History method.
	HistoryFunc func(ctx context.Context, id string, label string, lastN int) ([]LogValue, error)

	// InitializeFunc mocks the Initialize method.
	InitializeFunc func(contextMoqParam context.Context) error

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Label is the label argument value.
			Label string
			// Value is the value argument value.
			Value float64
			// Timestamp is the timestamp argument value.
			Timestamp time.Time
		}
		// AddFnct holds details about calls to the AddFnct method.
		AddFnct []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// FnType is the fnType argument value.
			FnType string
			// SubType is the subType argument value.
			SubType string
			// Tenant is the tenant argument value.
			Tenant string
			// Source is the source argument value.
			Source string
			// Lat is the lat argument value.
			Lat float64
			// Lon is the lon argument value.
			Lon float64
		}
		// History holds details about calls to the History method.
		History []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
			// Label is the label argument value.
			Label string
			// LastN is the lastN argument value.
			LastN int
		}
		// Initialize holds details about calls to the Initialize method.
		Initialize []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
	}
	lockAdd        sync.RWMutex
	lockAddFnct    sync.RWMutex
	lockHistory    sync.RWMutex
	lockInitialize sync.RWMutex
}

// Add calls AddFunc.
func (mock *FuncStorageMock) Add(ctx context.Context, id string, label string, value float64, timestamp time.Time) error {
	if mock.AddFunc == nil {
		panic("FuncStorageMock.AddFunc: method is nil but FuncStorage.Add was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ID        string
		Label     string
		Value     float64
		Timestamp time.Time
	}{
		Ctx:       ctx,
		ID:        id,
		Label:     label,
		Value:     value,
		Timestamp: timestamp,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, id, label, value, timestamp)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedFuncStorage.AddCalls())
func (mock *FuncStorageMock) AddCalls() []struct {
	Ctx       context.Context
	ID        string
	Label     string
	Value     float64
	Timestamp time.Time
} {
	var calls []struct {
		Ctx       context.Context
		ID        string
		Label     string
		Value     float64
		Timestamp time.Time
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// AddFnct calls AddFnctFunc.
func (mock *FuncStorageMock) AddFnct(ctx context.Context, id string, fnType string, subType string, tenant string, source string, lat float64, lon float64) error {
	if mock.AddFnctFunc == nil {
		panic("FuncStorageMock.AddFnctFunc: method is nil but FuncStorage.AddFnct was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ID      string
		FnType  string
		SubType string
		Tenant  string
		Source  string
		Lat     float64
		Lon     float64
	}{
		Ctx:     ctx,
		ID:      id,
		FnType:  fnType,
		SubType: subType,
		Tenant:  tenant,
		Source:  source,
		Lat:     lat,
		Lon:     lon,
	}
	mock.lockAddFnct.Lock()
	mock.calls.AddFnct = append(mock.calls.AddFnct, callInfo)
	mock.lockAddFnct.Unlock()
	return mock.AddFnctFunc(ctx, id, fnType, subType, tenant, source, lat, lon)
}

// AddFnctCalls gets all the calls that were made to AddFnct.
// Check the length with:
//
//	len(mockedFuncStorage.AddFnctCalls())
func (mock *FuncStorageMock) AddFnctCalls() []struct {
	Ctx     context.Context
	ID      string
	FnType  string
	SubType string
	Tenant  string
	Source  string
	Lat     float64
	Lon     float64
} {
	var calls []struct {
		Ctx     context.Context
		ID      string
		FnType  string
		SubType string
		Tenant  string
		Source  string
		Lat     float64
		Lon     float64
	}
	mock.lockAddFnct.RLock()
	calls = mock.calls.AddFnct
	mock.lockAddFnct.RUnlock()
	return calls
}

// History calls HistoryFunc.
func (mock *FuncStorageMock) History(ctx context.Context, id string, label string, lastN int) ([]LogValue, error) {
	if mock.HistoryFunc == nil {
		panic("FuncStorageMock.HistoryFunc: method is nil but FuncStorage.History was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		ID    string
		Label string
		LastN int
	}{
		Ctx:   ctx,
		ID:    id,
		Label: label,
		LastN: lastN,
	}
	mock.lockHistory.Lock()
	mock.calls.History = append(mock.calls.History, callInfo)
	mock.lockHistory.Unlock()
	return mock.HistoryFunc(ctx, id, label, lastN)
}

// HistoryCalls gets all the calls that were made to History.
// Check the length with:
//
//	len(mockedFuncStorage.HistoryCalls())
func (mock *FuncStorageMock) HistoryCalls() []struct {
	Ctx   context.Context
	ID    string
	Label string
	LastN int
} {
	var calls []struct {
		Ctx   context.Context
		ID    string
		Label string
		LastN int
	}
	mock.lockHistory.RLock()
	calls = mock.calls.History
	mock.lockHistory.RUnlock()
	return calls
}

// Initialize calls InitializeFunc.
func (mock *FuncStorageMock) Initialize(contextMoqParam context.Context) error {
	if mock.InitializeFunc == nil {
		panic("FuncStorageMock.InitializeFunc: method is nil but FuncStorage.Initialize was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockInitialize.Lock()
	mock.calls.Initialize = append(mock.calls.Initialize, callInfo)
	mock.lockInitialize.Unlock()
	return mock.InitializeFunc(contextMoqParam)
}

// InitializeCalls gets all the calls that were made to Initialize.
// Check the length with:
//
//	len(mockedFuncStorage.InitializeCalls())
func (mock *FuncStorageMock) InitializeCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockInitialize.RLock()
	calls = mock.calls.Initialize
	mock.lockInitialize.RUnlock()
	return calls
}
