// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package rules

import (
	"context"
	"sync"
)

// Ensure, that RuleStorageMock does implement RuleStorage.
// If this is not the case, regenerate this file with moq.
var _ RuleStorage = &RuleStorageMock{}

// RuleStorageMock is a mock implementation of RuleStorage.
//
//	func TestSomethingThatUsesRuleStorage(t *testing.T) {
//
//		// make and configure a mocked RuleStorage
//		mockedRuleStorage := &RuleStorageMock{
//			AddFunc: func(ctx context.Context, rule Rule) error {
//				panic("mock out the Add method")
//			},
//			DeleteFunc: func(ctx context.Context, id string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(ctx context.Context, id string) ([]Rule, []error, error) {
//				panic("mock out the Get method")
//			},
//			InitializeFunc: func(contextMoqParam context.Context) error {
//				panic("mock out the Initialize method")
//			},
//			UpdateFunc: func(ctx context.Context, rule Rule) error {
//				panic("mock out the Update method")
//			},
//		}
//
//		// use mockedRuleStorage in code that requires RuleStorage
//		// and then make assertions.
//
//	}
type RuleStorageMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, rule Rule) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, id string) error

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, id string) ([]Rule, []error, error)

	// InitializeFunc mocks the Initialize method.
	InitializeFunc func(contextMoqParam context.Context) error

	// UpdateFunc mocks the Update method.
	UpdateFunc func(ctx context.Context, rule Rule) error

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rule is the rule argument value.
			Rule Rule
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID string
		}
		// Initialize holds details about calls to the Initialize method.
		Initialize []struct {
			// ContextMoqParam is the contextMoqParam argument value.
			ContextMoqParam context.Context
		}
		// Update holds details about calls to the Update method.
		Update []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Rule is the rule argument value.
			Rule Rule
		}
	}
	lockAdd        sync.RWMutex
	lockDelete     sync.RWMutex
	lockGet        sync.RWMutex
	lockInitialize sync.RWMutex
	lockUpdate     sync.RWMutex
}

// Add calls AddFunc.
func (mock *RuleStorageMock) Add(ctx context.Context, rule Rule) error {
	if mock.AddFunc == nil {
		panic("RuleStorageMock.AddFunc: method is nil but RuleStorage.Add was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Rule Rule
	}{
		Ctx:  ctx,
		Rule: rule,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, rule)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedRuleStorage.AddCalls())
func (mock *RuleStorageMock) AddCalls() []struct {
	Ctx  context.Context
	Rule Rule
} {
	var calls []struct {
		Ctx  context.Context
		Rule Rule
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *RuleStorageMock) Delete(ctx context.Context, id string) error {
	if mock.DeleteFunc == nil {
		panic("RuleStorageMock.DeleteFunc: method is nil but RuleStorage.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, id)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedRuleStorage.DeleteCalls())
func (mock *RuleStorageMock) DeleteCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *RuleStorageMock) Get(ctx context.Context, id string) ([]Rule, []error, error) {
	if mock.GetFunc == nil {
		panic("RuleStorageMock.GetFunc: method is nil but RuleStorage.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  string
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, id)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedRuleStorage.GetCalls())
func (mock *RuleStorageMock) GetCalls() []struct {
	Ctx context.Context
	ID  string
} {
	var calls []struct {
		Ctx context.Context
		ID  string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// Initialize calls InitializeFunc.
func (mock *RuleStorageMock) Initialize(contextMoqParam context.Context) error {
	if mock.InitializeFunc == nil {
		panic("RuleStorageMock.InitializeFunc: method is nil but RuleStorage.Initialize was just called")
	}
	callInfo := struct {
		ContextMoqParam context.Context
	}{
		ContextMoqParam: contextMoqParam,
	}
	mock.lockInitialize.Lock()
	mock.calls.Initialize = append(mock.calls.Initialize, callInfo)
	mock.lockInitialize.Unlock()
	return mock.InitializeFunc(contextMoqParam)
}

// InitializeCalls gets all the calls that were made to Initialize.
// Check the length with:
//
//	len(mockedRuleStorage.InitializeCalls())
func (mock *RuleStorageMock) InitializeCalls() []struct {
	ContextMoqParam context.Context
} {
	var calls []struct {
		ContextMoqParam context.Context
	}
	mock.lockInitialize.RLock()
	calls = mock.calls.Initialize
	mock.lockInitialize.RUnlock()
	return calls
}

// Update calls UpdateFunc.
func (mock *RuleStorageMock) Update(ctx context.Context, rule Rule) error {
	if mock.UpdateFunc == nil {
		panic("RuleStorageMock.UpdateFunc: method is nil but RuleStorage.Update was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Rule Rule
	}{
		Ctx:  ctx,
		Rule: rule,
	}
	mock.lockUpdate.Lock()
	mock.calls.Update = append(mock.calls.Update, callInfo)
	mock.lockUpdate.Unlock()
	return mock.UpdateFunc(ctx, rule)
}

// UpdateCalls gets all the calls that were made to Update.
// Check the length with:
//
//	len(mockedRuleStorage.UpdateCalls())
func (mock *RuleStorageMock) UpdateCalls() []struct {
	Ctx  context.Context
	Rule Rule
} {
	var calls []struct {
		Ctx  context.Context
		Rule Rule
	}
	mock.lockUpdate.RLock()
	calls = mock.calls.Update
	mock.lockUpdate.RUnlock()
	return calls
}
